# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 07:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amazon_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ASIN', models.CharField(max_length=10)),
                ('financial', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('catId', models.CharField(max_length=20)),
                ('keywords', models.CharField(max_length=100)),
                ('selected', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AmazonVideoGames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amazon_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ASIN', models.CharField(max_length=10)),
                ('financial', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('catId', models.CharField(max_length=20)),
                ('keywords', models.CharField(max_length=100)),
                ('selected', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Ebay139971',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ebay_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('itemId', models.CharField(max_length=14)),
                ('financial', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ASINInfo', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('catId', models.CharField(max_length=20)),
                ('keywords', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('endTime', models.DateTimeField(null=True)),
            ],
        ),
    ]
