# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_auto_20170525_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmazonVideoGames',
            new_name='AmazonBook',
        ),
        migrations.RenameModel(
            old_name='AmazonBooks',
            new_name='AmazonVideoGame',
        ),
    ]
