# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_auto_20170526_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmazonBook',
            new_name='AmazonBooks',
        ),
        migrations.RenameModel(
            old_name='AmazonVideoGame',
            new_name='AmazonVideoGames',
        ),
    ]
