# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_auto_20170526_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonbooks',
            old_name='amazon_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='ebay139971',
            old_name='ebay_data',
            new_name='data',
        ),
    ]
