# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 22:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_auto_20170527_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebay139971',
            name='ASINInfo',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
