# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_auto_20170527_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonbooks',
            name='catId',
        ),
        migrations.RemoveField(
            model_name='amazonvideogames',
            name='catId',
        ),
        migrations.RemoveField(
            model_name='ebay139971',
            name='catId',
        ),
    ]
