# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_auto_20170528_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonvideogames',
            old_name='amazon_data',
            new_name='data',
        ),
    ]
