# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_auto_20170528_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonvideogames',
            name='keywords',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
