# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 02:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_auto_20170528_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonbooks',
            name='financial',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='amazonvideogames',
            name='financial',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='ebay139971',
            name='financial',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
