# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 02:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_auto_20170528_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebay139971',
            name='ASINList',
        ),
        migrations.AddField(
            model_name='ebay139971',
            name='ASINInfo',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
