# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 18:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_auto_20170528_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonvideogames',
            name='financial',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'current': {'TTP': 2, 'listPrice': 0.0, 'qty': 1}, 'historical': []}),
        ),
    ]
