# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_auto_20170528_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonbooks',
            name='type',
            field=models.CharField(default='game', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='amazonvideogames',
            name='type',
            field=models.CharField(default='game', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amazonvideogames',
            name='financial',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
