# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 05:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_auto_20170603_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebay48619',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('itemId', models.CharField(max_length=14)),
                ('financial', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('ASINInfo', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('keywords', models.CharField(max_length=100, null=True)),
                ('priced', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
