# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 06:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0017_ebay48619'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonElectronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ASIN', models.CharField(max_length=10)),
                ('type', models.CharField(default='game', max_length=10, null=True)),
                ('financial', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('keywords', models.CharField(max_length=100)),
                ('selected', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
