# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_amazonelectronics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ebay139971',
            new_name='EbayVideoGameConsoles',
        ),
    ]
