# Generated by Django 2.0.4 on 2018-04-25 23:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('UPC', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('financial', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('keywords', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EbaySources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('UPC', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('financial', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('keywords', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WalMartSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('UPC', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('financial', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('keywords', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
