# Generated by Django 2.0.4 on 2018-04-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmazonSources',
        ),
        migrations.DeleteModel(
            name='EbaySources',
        ),
        migrations.DeleteModel(
            name='WalMartSources',
        ),
    ]
