# Generated by Django 2.0.4 on 2018-06-01 00:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0004_auto_20180525_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_id', models.CharField(max_length=10)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Alibaba',
        ),
        migrations.DeleteModel(
            name='Amazon',
        ),
        migrations.DeleteModel(
            name='Ebay',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.DeleteModel(
            name='Walmart',
        ),
    ]
