# Generated by Django 2.0.6 on 2018-06-07 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemData',
        ),
    ]
